package configs

const (
	PORT_NO         = "PORT_NO"
	GRPC_PORT       = "GRPC_PORT"
	MONGO_USERNAME  = "MONGO_USERNAME"
	MONGO_PASSWORD  = "MONGO_PASSWORD"
	MONGO_AUTH      = "MONGO_AUTH"
	MONGO_URI       = "MONGO_URI"
	DB_NAME         = "DB_NAME"
	POST_COLLECTION = "post"
)
